### ISSUE TITLE
Add extra input fields

### ISSUE THREAD

**Issue by developius** [SubjectRefresh/Food#1]
User needs to be able to optionally input their weight, age and weight of the food they've got - unless we can get that from the API?

**Comment by pbexe** [comment]
@developius Can't it just be an estimate as that would detract from the UX and the flow of the program

**Comment by developius** [comment]
@pbexe I added this functionality in c29234c744896e9f281ec2a8056e2fda23f7ca7f but maybe we could have them as an 'optional' dropdown that reveals them?

**Comment by pbexe** [comment]
@developius Good idea. Most people using this site wouldn't be serious about exact figures, just ass rough estimate. So the option is good

**Comment by developius** [comment]
@pbexe yeah :D

**Comment by pbexe** [comment]
Well... That didnt work

**Comment by developius** [comment]
@pbexe :stuck_out_tongue_winking_eye:
